send:
    path: /send
    controller: App\Controller\SendCertificatePostController
    methods: [ POST ]

certificate:
    path: /certificate
    controller: App\Controller\CertificateGetController
    methods: [ GET ]
