version: '3'

services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=food
      - MYSQL_USER=food
      - MYSQL_PASSWORD=food
      - MYSQL_ROOT_PASSWORD=food
  php:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    command: symfony serve --dir=/app --force-php-discovery
  blackfire:
    image: blackfire/blackfire:2
    ports: [ "8307" ]
    env_file:
      - ./.env.docker
