version: '3'

services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=codely
      - MYSQL_USER=codely
      - MYSQL_PASSWORD=codely
      - MYSQL_ROOT_PASSWORD=codely
  php:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    command: symfony serve --dir=/app --force-php-discovery