language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install: composer update $COMPOSER_FLAGS --prefer-dist

after_failure: "cat /home/travis/build/gimler/symfony-rest-edition/app/logs/test.log"

script: phpunit -c app
