send_email:
    path: /email-preview/send
    controller: App\EmailPreview\Controller\SendEmailController::send

log:
    path: /logger/log
    controller: App\Logger\Controller\LogController::log

profiler_parameter:
    path: /profiler-parameter
    controller: App\ProfilerParameter\Controller\ProfilerParameterController::index

abstract_controller:
    path: /abstract-controller
    controller: App\AbstractController\Controller\HomeController
