parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\EmailPreview\Controller\:
        resource: '../src/EmailPreview/Controller/'
        tags: ["controller.service_arguments" ]

    App\Logger\Controller\:
        resource: '../src/Logger/Controller/'
        tags: ["controller.service_arguments" ]

    App\ProfilerParameter\Controller\:
        resource: '../src/ProfilerParameter/Controller/'
        tags: ["controller.service_arguments" ]
