monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
            formatter: monolog.formatter.json
        chromephp:
            type: chromephp
            channels: ["domain_event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        domain_event:
            type: stream
            path: "%kernel.logs_dir%/domain_event_%kernel.environment%.log"
            channels: ["domain_event"]
