food_bulk_insert:
    path: /food-bulk-insert
    controller: App\Controller\FoodBulkPostController
    methods: [ GET ]

feed_food:
    path: /feed/food
    controller: App\Controller\ProcessFeedGetController
    methods: [ GET ]
